### PR TITLE
Add basic portfolio

### PR DESCRIPTION
**Pull request by riyakb**

### CODE REVIEW

**Comment by nityendrasingh** [comment]
Can you post the link that displays the portfolio?

**Comment by riyakb** [comment]
http://rbaviskar-sps-summer20.appspot.com/

**Comment by nityendrasingh** [comment]
It doesn't work well for me. 
Screenshot 2020-07-14 at 9 40 22 PM

**Comment by nityendrasingh** [comment]
Sorry, I didn't know I had to click the close button. :)

**Review by nityendrasingh — APPROVED** [review]
Nice! Good job 👍

**Pull request merged**
